name: GitHub Actions EVs demo
run-name: ${{ github.actor }} is testing out GitHub Actions EVs on ${{ runner.os }} machine 🚀
on:
  workflow_dispatch:
  push:
jobs:
  job01:
    runs-on: ubuntu-latest
    env:
      USERNAME: "job01 user"
      URL: "job01_URL"
    steps:
      - name: Print the USERNAME envs
        run: | 
          echo $USERNAME
          echo $URL
          echo ${{ env.USERNAME }}
      - name: Print the USERNAME envs in step 2
        env:
          USERNAME: "job01 step 2 user"
        run: | 
          echo $USERNAME
          echo $URL
          echo ${{ env.USERNAME }}
  job02:
    runs-on: ubuntu-latest
    steps:
      - name: Print the USERNAME envs
        run: | 
          echo $USERNAME
          echo $URL
          echo ${{ env.USERNAME }}
